### ISSUE TITLE
Impossible to get the code

### ISSUE THREAD

**Issue by ThHareau** [Happening/Docs#1]
I'm trying to follow the _Your first pluggin_ page.  
I can't deploy my code. I get the error _Invalid upload code_.  
According to this article, it may be possible to get it in the setting tab. I don't see any code there... 
Is there another way to get it ?

**Comment by Zenkala** [comment]
Hey Entilore

To find the plugin settings page navigate the following:
- Go to "My group apps" on happening.im
  This reviels the list of the plugins you made.
- On the right hand side of "My Group App" is an terminal icon. That leads to the settings page.
- Here too is a quickstart explanation. The last line of it is "./deploy <long code here>". That's the deploy code.

**Comment by ThHareau** [comment]
Okay, thanks a lot.
